name: Angular-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4.1.0

      - name: Install dependences
        run: npm install

      - name: Build Angular APP
        run: npm run build:prod

      - name: Rename Index.csr.html to index.html
        run: mv dist/angular_tutorial/browser/index.csr.html dist/angular_tutorial/browser/index.html

      - name: Deploy Github pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/angular-tutorial/browser
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
